controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_show:
    path: /product/show/{id}/{page}
    controller: App\Controller\ProductController::show
    requirements:
        id: \d+
        page: \d+
    defaults:
        page: 1
        id: 1

product_sort:
    path: /product/sort/{id}
    controller: App\Controller\ProductController::sort
    requirements:
        id: \d+
    defaults:
        id: 1

product_add:
    path: /product/add
    controller: App\Controller\ProductController::add


product_search:
    path: /product/search
    controller: App\Controller\ProductController::search
    methods: GET

product_viewing:
    path: /product/viewing/{id}
    controller: App\Controller\ProductController::viewing
    requirements:
        id: \d+
<<<<<<< HEAD
    defaults:
        id: 1
=======
>>>>>>> origin/main


