controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_show:
    path: /product/show/{id}/{page}
    controller: App\Controller\ProductController::show
    requirements:
        id: \d+
        page: \d+
    defaults:
        page: 1
        id: 1

product_sort:
    path: /product/sort/{id}
    controller: App\Controller\ProductController::sort
    requirements:
        id: \d+
    defaults:
        id: 1

product_add:
    path: /product/add
    controller: App\Controller\ProductController::add


product_search:
    path: /product/search
    controller: App\Controller\ProductController::search
    methods: GET

product_viewing:
    path: /product/viewing/{id}
    controller: App\Controller\ProductController::viewing
    requirements:
        id: \d+
    defaults:
        id: 1

default_login:
    path: /default/login
    controller: App\Controller\DefaultController::login

default_about:
    path: /default/about
    controller: App\Controller\DefaultController::about

product_cart:
    path: /product/cart
    controller: App\Controller\ProductController::cart

default_home:
    path: /
    controller: App\Controller\DefaultController::home

product_detail:
    path: /product/detail_1/{id}
    controller: App\Controller\ProductController::product_detail
    requirements:
        id: \d+


product_category:
    path: /product/category
    controller: App\Controller\ProductController::product_category

default_latestNews:
    path: /default/latestNews
    controller: App\Controller\DefaultController::latestNews

default_newsOne:
    path: /default/newsOne/{id}
    controller: App\Controller\DefaultController::newsOne
    requirements:
        id: \d+

feedback_form:
    path: /feedback
    controller: App\Controller\DefaultController::feedback


default_contacts:
    path: /default/contacts
    controller: App\Controller\DefaultController::contacts

cart_cart:
    path: /cart/cart
    controller: App\Controller\CartController::cart

default_newsList:
    path: /default/newsList
    controller: App\Controller\DefaultController::newsList

export_newsList:
    path: /default/exportList
    controller: App\Controller\DefaultController::exportList

admin_comments:
    path: /admin/commentsList
    controller: App\Controller\Admin\AdminController::commentsList
